Script started on 2022-11-14 16:56:21-08:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]777;notify;Command completed;exit\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ echo $USERNAME
[?2004l
]777;preexec\idane
]777;notify;Command completed;echo $USERNAME\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ export $[KPATH=$PATH:.
[?2004l
]777;preexec\]777;notify;Command completed;export PATH=$PATH:.\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ echo $PATH
[?2004l
]777;preexec\/usr/lib/java/apache-ant-1.10.12/bin:/usr/lib/java/apache-ant-1.10.12/bin:/home/idane/.local/bin:/home/idane/bin:/usr/lib/java/apache-ant-1.10.12/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:.
]777;notify;Command completed;echo $PATH\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ W[Kecho $PATHxport PATH=$PATH:.[5Pcho $USERNAMExit[Kscatterplot.Rrunanalysis dataout urllistgeturls urllist lecturelist.html
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[A[35Pexport PATH=$PATH:.

[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html
[?2004l
]777;preexec\--2022-11-14 16:56:59--  https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html
Resolving courses.cs.washington.edu (courses.cs.washington.edu)... 128.208.1.193, 2607:4000:200:10::c1
Connecting to courses.cs.washington.edu (courses.cs.washington.edu)|128.208.1.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11687 (11K) [text/html]
Saving to: ‘lecturelist.html’


lecturelist.html      0%[                    ]       0  --.-KB/s               
lecturelist.html    100%[===================>]  11.41K  --.-KB/s    in 0s      

2022-11-14 16:56:59 (197 MB/s) - ‘lecturelist.html’ saved [11687/11687]

]777;notify;Command completed;wget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ wget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[Aecho $PATH[K

[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cxport PATH=$PATH:.[5Pcho $USERNAMExit[Kscatterplot.R[K[K[K[K[K[K[K[K[K[K[K[K[Krunanalysis dataout urllistgeturls urllist lecturelist.html
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[A[22Pgeturls urllist lecturelist.html

[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[?2004l
]777;preexec\Warning: ./geturls overwritting file urllist
]777;notify;Command completed;geturls urllist lecturelist.html\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ geturls urllist lecturelist.html
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[Aecho $PATH[K

[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cxport PATH=$PATH:.[5Pcho $USERNAMExit[K[Krunanalysis dataout urllist
[?2004l
]777;preexec\Warning: ./runanalysis overwritting existing dataout
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/hello.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/magic.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/printargs.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/square1.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control2.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/fgets.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/argumentdemo.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/dangling.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/pointeradd.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery1.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery2.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery3.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery4.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydemo.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydynamic.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_orig.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_fixed.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_orig.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_fixed.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arrdynamicwrong.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mysterynum.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/point.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist_1.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlistclient.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/debug.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/twice.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/main.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/speak.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/shout.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/curve.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/test.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/for.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/testfor.c...
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/hexdemo.c...
...successful
]777;notify;Command completed;runanalysis dataout urllist\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ runanalysis dataout urllistgeturls urllist lecturelist.html
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwget https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[Aecho $PATH[K

[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[Kscatterplot.R
[?2004l
]777;preexec\[1] 3628
[1] 98.05405
null device 
          1 
]777;notify;Command completed;scatterplot.R\]777;precmd\]0;idane@localhost:~/cse374\]7;file://localhost/home/idane/cse374\[?2004h[idane@localhost cse374]$ exit
[?2004l
]777;preexec\exit

Script done on 2022-11-14 16:57:49-08:00 [COMMAND_EXIT_CODE="0"]

#Ishan Dane 11/14/2022
#Based on the scatterplot printed by scatterplot.R, we can see that there is 
#no real trend occuring with out scatterplot. We can see that at the start, 
#the data follows a linear correlation, however, after the first 10 courses,
#the index sizes vary significantly, showing no correlation between index size
#and courses. The maximum value exists at 25 course 25 with an index size that
#is bigger than 350. The minimum value exists at course 35 with a value of
#around 10. This shows a random arrangement of the scatterplot and so no real
#trend conclusion can be found. 
#The 2 values provided by the R script are: The first value provides information 
#on the sum of all the files' index sizes (sum of words from all c files). The second value 
#provides information on the average index size (word count) for all the courses (c files).  
